### ISSUE TITLE
Sack of Rice Loot Table missing

### ISSUE THREAD

**Issue by Burgersim** [Farcr/SwampExpansion#34]
I noticed that in my version of the mod (swampexpansion-1.15.2-1.6.1.jar) sack of rice didn't drop the block, when I broke it. It was an easy fix to add the loot table for it, but still, I thought it would be nice to open an issue ^^

**Comment by bageldotjpg** [comment]
Fixed in 2c24cfb485a0f4d759798f82f3c7ab379909586a
