### ISSUE TITLE
[1.15.2] Missing Forge Biome Types in Biome Dictionary

### ISSUE THREAD

**Issue by jrkulmer** [Farcr/SwampExpansion#38]
```[27May2020 00:00:51.015] [modloading-worker-3/WARN] [net.minecraftforge.common.BiomeDictionary/]: No types have been added to Biome swampexpansion:mushroom_marsh, types have been assigned on a best-effort guess: [SWAMP, WET]```

Forge Version: 3.1.20
Swamp Expansion Version: 1.7.1

Looks like the Biome dictionary is missing a registration for mushroom marsh.

**Comment by bageldotjpg** [comment]
Will be fixed in next release, thanks.
