### ISSUE TITLE
[1.15.2] [Compatibility] Terraforged - Marsh doesn't generate

### ISSUE THREAD

**Issue by jrkulmer** [Farcr/SwampExpansion#39]
Forge Version: 3.1.20
Abnormal's Core Version: 1.0.4
Swamp Expansion Version: 1.7.1
Terraforged Version: 0.0.14
Nature's Compass Version: 1.8.6

When using Swamp Expansion on the "Terraforged" world type, Marsh biomes do not generate. I don't have a method to conclusively prove this, but I used the Nature's compass mod to do several (>10) distantly separated checks (the mod searches within a 10,000 radius of the player), on >5 seeds for the biome, and nothing came up every time.

**Comment by bageldotjpg** [comment]
Not really much I can do about this one, likely a problem with TerraForged custom world and since I've never used it I can't really identify the problem which is likely on their end, sorry.
