### ISSUE TITLE
[1.15.2] Missing data fixer registration for Slabfish

### ISSUE THREAD

**Issue by jrkulmer** [Farcr/SwampExpansion#40]
Forge Version: 3.1.20
Swamp Expansion Version: 1.7.1

Missing data fixer registration for slabfish.

```[27May2020 00:15:43.872] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity swampexpansion:slabfish```

**Comment by bageldotjpg** [comment]
This will happen for all modded entities, it's not an issue
