### ISSUE TITLE
[Suggestion] Mud and Clay Monsters - New Hostile Mob exclusive to Swamps!

### ISSUE THREAD

**Issue by SpiderKolo** [Farcr/SwampExpansion#43]
Hostile Mob exclusive to Swamps.
It spawns in one of two variants: Mud or Clay.
Mud Monster on death would drop a bit of dirt and a lot of mud, making Dirt Renewable.
Clay monster on death would give some plenty of Clay blocks and pieces, making Clay renewable outside Raid Farms.
Both variants could also drop Sticks, rarely Slime, and when killed with fire - "cooked" version of their drops (Clay into Bricks and Terracotta, Mud into Dirt). They also can absorb items it touches, which also drop when you kill monster.
There would be also a very rare drop - Mud Monsters Eye which can be used for new special block.
Don't know yet what that eye would do, but it would be fitting if it was related to Swamp biomes in some way...

Mud/Clay monster would spawn only at dark or when raining/thundering specifically on Swamp and take damage from sunlight.
It could have around 15 hearts of health, would hit hard while close to player but be a bit slow, but could throw blocks of Mud at the player.

Turns list of Dirt related blocks into Dirt when walking on them or when projectile hits those blocks.
This ability could be turned off in configuration file or by gamerule for mob griefing.
 
It's immune to Knockback, and while in Swamp - also to fire, but while in Desert, other dry Biom or in Nether, it would keep taking damage from heat and no longer be immune to burn effect.

When player takes damage from Mud/Clay monster, it gains slowness effect making it potentially more difficult to retreat. It also deals more damage compared to other monsters, but attacks are very slow  and can be blocked by shield or by hiding behind blocks.

**Comment by bageldotjpg** [comment]
We do have some form of Swamp monster planned, likely a bit different from this. We don't usually take suggestions/ideas for github but if you'd like to discuss your ideas a bit better and maybe with other people you could join our discord. Thank you for the idea though!
