### ISSUE TITLE
underwaterHoe RightClickBlock event breaks any UseHoeEvent

### ISSUE THREAD

**Issue by Insane96** [Farcr/SwampExpansion#45]
With the latest Swamp Expansion update my changes to hoe no longer work, in my mod I've basically added a cooldown to hoes, but no longer works: https://github.com/Insane96/IguanaTweaksReborn/blob/1.15.2/src/main/java/insane96mcp/iguanatweaksreborn/modules/FarmingModule.java#L311

I've checked SwampEx code and found this https://github.com/Farcr/SwampExpansion/blob/master/src/main/java/com/farcr/swampexpansion/core/other/SwampExEvents.java#L109
Seems like `RightClickBlock` is called before `UseHoeEvent`, thus ignoring my event and changes

I think this basically breaks any mod that uses `UseHoeEvent`

**Comment by bageldotjpg** [comment]
I changed how it work, test if it does now. Reopen if so
