### ISSUE TITLE
[1.15.2] [Compatibility] Terraforged - Swamp Expansion's biomes won't generate with Terraforge.

### ISSUE THREAD

**Issue by HauntedSniper** [Farcr/SwampExpansion#46]
After reading issues with Terraforged, it seems like someone has noticed that SE biomes won't generate. The developer answer was that this issue happens because SE apparently doesn't make use of the BiomeDictionary  BiomeType "overworld", which Terraforged uses to know which biomes to generate.

If possible it would be of great help that the biomes on SwampExpansion are marked with the BiomeType "overworld" to be selectable for generation with this mod.

**Comment by bageldotjpg** [comment]
They do now!
