### ISSUE TITLE
Foliage seems unaffected by Quark's greener grass feature.

### ISSUE THREAD

**Issue by Aero48** [Farcr/SwampExpansion#48]
I've observed this with willow leaves, giant tall grass, and duckweed even when added to the greener grass whitelist in quark's config file. This problem seems to be exclusive to the latest version of the mod (1.7.2)

**Comment by bageldotjpg** [comment]
Do you know any other mods that have foliage that works with Greener Grass?
I don't ever use greener grass so I've never seen or experienced this.
