### ISSUE TITLE
Rice not tagged for compatibility with other mods.

### ISSUE THREAD

**Issue by laserlemons** [Farcr/SwampExpansion#51]
I copied the following tags from the rice from the mod Farmer's Delight:

> forge:seeds/rice
> forge:crops/rice
> forge:grain/rice

I believe Pam's Harvestcraft uses those same tags.

**Comment by bageldotjpg** [comment]
1.15 isn't going to be updated but I believe farmer's delight plans on handling this on their own end when they add some compatibility
