### ISSUE TITLE
How do I stop the giant tall grass from being generated?

### ISSUE THREAD

**Issue by ghost** [Farcr/SwampExpansion#58]
I want to remove the new grass altoguether,because in BoP it generates in most biomes even those unrelated to swamps.. .. I have OCD,so the grass gets really noticeable for me,especially with shaders that add shadows...

**Comment by bageldotjpg** [comment]
Unfortunately there is no way to stop the generation of Giant Tall Grass... this will be possible in the 1.16 port and rebrand but unfortunately not for 1.15. Sorry. If you are somewhat familiar with code you can try editing the jar.
